[package]
name = "aril-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "aril"
path = "src/main.rs"

[dependencies]
aril-core = { workspace = true, features = ["parallel"] }
clap = { workspace = true }
clap_complete = "4.5"
anyhow = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

